---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{namespace}}-pv
  labels:
    app: {{namespace}}-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{nfs-artifact-path}}
    server: {{nfs-server}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: {{namespace}}
 name: {{namespace}}-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     app: {{namespace}}-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{namespace}}-pvdata
  labels:
    app: {{namespace}}-pvdata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{nfs-fabric-data-path}}
    server: {{nfs-server}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: {{namespace}}
 name: {{namespace}}-pvdata
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
 selector:
   matchLabels:
     app: {{namespace}}-pvdata

